name: "Setup gscache"
description: "Setup gscache for Go builds"
author: "breezewish"
inputs:
  version:
    description: "Version of gscache to download"
    required: false
    default: ""
  storage:
    description: "Cache storage location, like s3://bucket"
    required: true
  debug:
    description: "Enable debug logging"
    required: false
    default: "false"
  github-token:
    description: "GitHub token for authenticated requests to avoid rate limiting"
    required: false
    default: ""
runs:
  using: "node20"
  main: "dist/index.js"
branding:
  icon: "download"
  color: "blue"
